In [2]:
#importing packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [5]:
#import data
df=pd.read_csv("spam.csv")

In [7]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [9]:
#inspect data
df.groupby('v1').describe()

v2                                                                 \
     count unique                                                top freq   
v1                                                                          
ham   4825   4516                             Sorry, I'll call later   30   
spam   747    653  Please call our customer service representativ...    4   

     Unnamed: 2                                                            \
          count unique                                                top   
v1                                                                          
ham          45     39   bt not his girlfrnd... G o o d n i g h t . . .@"   
spam          5      4                                        PO Box 5249   

          Unnamed: 3                                    Unnamed: 4         \
     freq      count unique                    top freq      count unique   
v1                                                                          
ham     3         10      9                     GE    2          6      5   
spam    2          2      1   MK17 92H. 450Ppw 16"    2          0      0   

                    
          top freq  
v1                  
ham   GNT:-)"    2  
spam      NaN  NaN

In [10]:
#converting ham/spam into numerical values
df['spam']=df['v1'].apply(lambda x:1 if x=='spam' else 0)

In [13]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  spam  
0           NaN        NaN     0  
1           NaN        NaN     0  
2           NaN        NaN     1  
3           NaN        NaN     0  
4           NaN        NaN     0  
...         ...        ...   ...  
5567        NaN        NaN     1  
5568        NaN        NaN     0  
5569        NaN        NaN     0  
5570        NaN        NaN     0  
5571        NaN        NaN     0  

[5572 rows x 6 columns]

In [11]:
#spliting train and test
x_train,x_test,y_train,y_test=train_test_split(df.v2,df.spam,test_size=0.25)

In [12]:
x_train.describe()

count                       4179
unique                      3924
top       Sorry, I'll call later
freq                          24
Name: v2, dtype: object

In [16]:
#find word count and storing as a matrix
cv=CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [18]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
#Train model
model = MultinomialNB()
model.fit(x_train_count,y_train)

MultinomialNB()

In [22]:
#Pre-Testing ham
email_ham=["hey wanna meet up for the game?"]
email_ham_count=cv.transform(email_ham)
model.predict(email_ham_count)

array([0], dtype=int64)

In [23]:
#Pre-Testing spam
email_spam=['reward money click']
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1], dtype=int64)

In [25]:
#Test model
x_test_count = cv.transform(x_test)
model.score(x_test_count,y_test)

0.9877961234745154